<?php

namespace App\Http\Controllers\Client;

use App\Credit;
use App\Http\Controllers\Controller;
use UserAttr;
use Illuminate\Http\Request;

class CreditController extends Controller
{
    public function index()
    {
        $user = auth()->user();
        $credit = Credit::where('user_id', $user->id)->get();

        $dept_max = auth()->user()->UserAttr()->where('user_id', $user->id)->first()->dept_max;

        return view('client.credit', compact('credit', 'dept_max'));
    }
    public function add_credit(Request $request)
    {
        $validate = $request->validate([
            'value' => ['required', 'numeric', 'min:1000'],
        ]);
  
          // وارد صفحه پرداخت میشه
     
            $merchant_id = "354c9418-c7a3-4dc7-b49c-0c42b660daf1";
            $phone = auth()->user()->phone;
            $amount = $request->value * 10;//rial to toman
            $user_id = auth()->user()->id;

            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, 'https://api.zarinpal.com/pg/v4/payment/request.json');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_POST, 1);

            curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"merchant_id\": \"$merchant_id\",\n  \"amount\": $amount,\n  \"callback_url\": \"http://medicjoo.com/credit_added?amount=$amount&user_id=$user_id\",\n  \"description\": \"پرداخت آنلاین مدیکجو\",\n  \"metadata\": {\"mobile\": \"$phone\",\"email\": \"mail@medicjoo.com\"}\n}");
            
            $headers = array();
            $headers[] = 'Accept: application/json';
            $headers[] = 'Content-Type: application/json';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
            
            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close($ch);
            $auth = json_decode($result)->data->authority ?? '';
            header("Location: https://www.zarinpal.com/pg/StartPay/" . $auth);
            exit;





    }

    public function credit_added(Request $request){
        if($request->Status == "OK"){
        $user = auth()->user();
        $credit = Credit::create([
            'user_id' => $request->user_id,
            'change' => $request->amount / 10 ,
        ]);
        return redirect()->route('client_credit')->with('msg', 'تراکنش موفق');
    }else{
        return redirect()->route('client_credit')->withErrors('تراکنش ناموفق بود');
        }
    }


    public function add_debt(Request $request)
    {
 
      

        $validate = $request->validate([
            'value' => ['required', 'numeric'],
        ]);

        $user = auth()->user();
        $debt = Credit::create([
            'user_id' => $user->id,
            'change' => $request->value,
        ]);
        return redirect()->back()->with('msg', 'تراکنش موفق');
    }


    public function pay_debt(Request $request)
    {
        $validate = $request->validate([
            'value' => ['required', 'numeric', 'min:1000'],
        ]);

        $user_debt = auth()->user()->credit()->sum('debt');
        if ($request->value > $user_debt) {
            return redirect()->back()->withErrors('مبلغ واریزی از میزان بدهی شما بیشتر است');
        }

        $user = auth()->user();
        $credit = Credit::create([
            'user_id' => $user->id,
            'change' => -1 * $request->value,
            'debt' => -1 * $request->value,
        ]);

        return redirect()->back()->with('msg', 'تراکنش موفق');
    }
}
